### ISSUE TITLE
Unexpected total loss when target image = original image

### ISSUE THREAD

**Issue by parashar-gaurav** [pankessel/explanations_can_be_manipulated#2]
Hello! I was trying different things with this code base, and when I ran the attack (run_attack.py) with the same target image as the original image (tiger_cat.jpg), I expected the initial total loss to be 0.0 (as MSE Loss between explanations should be 0). But, the initial total loss started with some other value and then gradually converged to 0.0. I am unable to understand this behavior.

![Screenshot_2021-05-17 Google Colaboratory](https://user-images.githubusercontent.com/58598885/118494775-20bd5100-b740-11eb-9b4f-0988fbfbabf1.png)

**Comment by parashar-gaurav** [comment]
same when both the original and target image were collie4.jpeg
![Screenshot_2021-05-17 Google Colaboratory(1)](https://user-images.githubusercontent.com/58598885/118495184-94f7f480-b740-11eb-9621-f89532c69c67.png)

**Comment by annahdo** [comment]
Hi parash-gaurav,

thanks for the interest in our work.

If you look closely at the two examples you posted, the initial total loss is on the order of $10^{-13}$, a very small number that is approximately zero. 
This small deviation from 0.0 probably arises due to numerical inaccuracies inherent in floating-point computations.
